# Generated by Django 2.2.16 on 2022-09-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
    ]
